pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }
}

rootProject.name = 'jmcomic-api-java'

include ':jmcomic-api'
include ':jmcomic-core'
include ':jmcomic-android-support'
include ':jmcomic-sample'
